/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_hthcorp_llama_LlamaModel */

#ifndef _Included_cn_hthcorp_llama_LlamaModel
#define _Included_cn_hthcorp_llama_LlamaModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_hthcorp_llama_LlamaModel
 * Method:    embed
 * Signature: (Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cn_hthcorp_llama_LlamaModel_embed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_hthcorp_llama_LlamaModel
 * Method:    encode
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_hthcorp_llama_LlamaModel_encode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_hthcorp_llama_LlamaModel
 * Method:    setLogger
 * Signature: (Lcn/hthcorp/llama/args/LogFormat;Ljava/util/function/BiConsumer;)V
 */
JNIEXPORT void JNICALL Java_cn_hthcorp_llama_LlamaModel_setLogger
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cn_hthcorp_llama_LlamaModel
 * Method:    requestCompletion
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_hthcorp_llama_LlamaModel_requestCompletion
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_hthcorp_llama_LlamaModel
 * Method:    receiveCompletion
 * Signature: (I)Lcn/hthcorp/llama/LlamaOutput;
 */
JNIEXPORT jobject JNICALL Java_cn_hthcorp_llama_LlamaModel_receiveCompletion
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_hthcorp_llama_LlamaModel
 * Method:    cancelCompletion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_hthcorp_llama_LlamaModel_cancelCompletion
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_hthcorp_llama_LlamaModel
 * Method:    decodeBytes
 * Signature: ([I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_hthcorp_llama_LlamaModel_decodeBytes
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     cn_hthcorp_llama_LlamaModel
 * Method:    loadModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_hthcorp_llama_LlamaModel_loadModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_hthcorp_llama_LlamaModel
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_hthcorp_llama_LlamaModel_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
